### PR TITLE
Update analyze package versions

### PR DESCRIPTION
**Pull request by albennett**
## Description
Update analyze packages
https://buffer.slack.com/archives/C151RRDL1/p1570487151098400

## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by federicoweber** [comment]
Hey @albennett sorry I think we pushed a small update this morning as well, can we push it to ` v1.12.1` 😄 ?

One thing we will also need to update the RPC endpoints, to match the new one, let me know if you need a hand with those 🙂.

**Comment by albennett** [comment]
hey @federicoweber it looks like the `@bufferapp/server-analyze` is the only one that's `v1.12.1` and we're not importing it. 

Also, we're using logic to check if we should use the analyze api https://github.com/bufferapp/buffer-publish/blob/master/packages/server/rpc/analytics/compare/index.js#L14

Are you saying that we don't need to check anymore and instead default to the analyze api?

**Comment by federicoweber** [comment]
Oh you are right @albennett, sorry I didn't notice that.

Yep that's right we are getting also Twitter data from Analyze API. So I think you want to replace all RPC endpoints in https://github.com/bufferapp/buffer-publish/tree/master/packages/server/rpc/analytics with the ones from Analyze (note that `postsAnalyzeApi` has been deprecated, we are using only `posts` now).

ps. might be worth to double-check if there is any difference in global variables names for the API address, I think you use some different ones in Publish.

**Comment by albennett** [comment]
Great, thanks @federicoweber ! It looks like the endpoints are coming through ok. Regarding `analyticStartDate` & `audience` rpc packages -- are they also deprecated? 

I also noticed new rpc endpoints have been added to the `getReport` rpc package. Can you confirm these new endpoints are not needed for the publish charts?

**Comment by federicoweber** [comment]
oh I noticed that tests for `postsSummary` are failing, worth fixing those before merging 😉

**Pull request merged**
