### PR TITLE
Adjust cpu and memory requests and limits

### PR DESCRIPTION
**Pull request by erickhun**
- Removed the CPU limit to improve latency. 
- `latencySensitive: true` will schedule the pods in specific nodes 
More context in https://threads.com/34383695761

I've also changed cpu and memory request based [on current usage](https://app.datadoghq.com/dashboard/e6n-9bx-ru6/cpu-usage--requests--throttle-analysis?from_ts=1597328836694&live=false&to_ts=1597390366031&tpl_var_app=buffer-publish&tpl_var_namespace=buffer) 

cc @karelm  @hamstu @anafilipadealmeida @albennett @MayaUribe

### CODE REVIEW

**Comment by erickhun** [comment]
should I worry about cypress tests failing @hamstu 🤔  ?

**Comment by MayaUribe** [comment]
> should I worry about cypress tests failing @hamstu 🤔 ?

Hey @erickhun! I wouldn't worry too much about the cypress tests failing, we've been having some problems with them, and are still working in making them consistently work 😅 seems like a timing issue at times, you could try to re-trigger it if you feel more comfortable with those passing 😊

**Comment by erickhun** [comment]
Thanks @MayaUribe ! it worked after 2 dummy commits !

Is that okay for you ot review it to unblock the deploy? 🙇

**Comment by MayaUribe** [comment]
> Thanks @MayaUribe ! it worked after 2 dummy commits !
> 
> Is that okay for you ot review it to unblock the deploy? 🙇

Yes of course! 🚀

**Review by MayaUribe — APPROVED** [review]

**Pull request merged**
