### PR TITLE
Send x-buffer-client-id to Core RPC API

### PR DESCRIPTION
**Pull request by philippemiguet**
Send x-buffer-client-id to Core RPC API + update to latest micro-rpc-client version 🙌 

## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [x] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by philippemiguet** [comment]
Hey @hamstu can you help me merge this PR? I'm not sure why the build keeps on failing there? 🤔

**Comment by hamstu** [comment]
Hey @philippemiguet. Ah yeah, it looks like the analyze components we include in Publish are the culprit here. They often give us trouble like this. 

```
ERROR in ./node_modules/@bufferapp/analyze-date-picker/node_modules/@bufferapp/async-data-fetch/middleware.js
Module not found: Error: Can't resolve 'micro-rpc-client' in '/src/node_modules/@bufferapp/analyze-date-picker/node_modules/@bufferapp/async-data-fetch'
 @ ./node_modules/@bufferapp/analyze-date-picker/node_modules/@bufferapp/async-data-fetch/middleware.js 13:45-72
 @ ./node_modules/@bufferapp/analyze-date-picker/node_modules/@bufferapp/async-data-fetch/index.js
 @ ./node_modules/@bufferapp/analyze-date-picker/middleware.js
 @ ./node_modules/@bufferapp/analyze-date-picker/index.js
 @ ./node_modules/@bufferapp/average-table/middleware.js
 @ ./packages/analytics/components/AnalyticsList/store.js
 @ ./packages/analytics/components/AnalyticsList/index.jsx
 @ ./packages/analytics/components/Analytics/index.jsx
 @ ./packages/analytics/index.js
 @ ./packages/profile-page/components/ProfilePage/index.jsx
 @ ./packages/profile-page/index.js
 @ ./packages/app-pages/components/ProfilePages/index.jsx
 @ ./packages/app-pages/components/AppPages/index.jsx
 @ ./packages/app-pages/index.js
 @ ./packages/web/components/App/index.jsx
 @ ./packages/web/index.jsx
 @ multi core-js/stable regenerator-runtime/runtime ./packages/web/index.jsx
```

Can you try adding back `'micro-rpc-client'` to the package.json?

**Comment by philippemiguet** [comment]
@hamstu, cypress is still failing and I'm not sure how that is related to my change there? 🤔

**Comment by hamstu** [comment]
Thanks @philippemiguet!

Ah yeah, Cypress will be failing now due to the staging issues I mentioned here: https://threads.com/34397686227

I'm curious, are you able to load the staging branch to test (https://enrich-dd-publish.dev.buffer.com/)? As mentioned in my Thread I can't load any of them now. Unless we find another way, it might be best to wait until we've temporarily reverted the staging changes to test / merge this in.

**Comment by philippemiguet** [comment]
Yes, finally all greeeeeeeeen 😄

**Pull request merged**
