### PR TITLE
[PUB-3615] Request calendar data with browser timezone

### PR DESCRIPTION
**Pull request by anafilipadealmeida**
### Description

Request calendar data with browser timezone
- Add timezone as variable in the calendar queries
- Create getTimezoneFromBrowser util
### Context & Notes
https://buffer.atlassian.net/browse/PUB-3615

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] I have tested different user stories.
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
image

### CODE REVIEW

**Comment by anafilipadealmeida** [comment]
I'm a bit puzzled by this one @hamstu, as soon as I pass the timezone in the query, the weekly posts disappear, but the monthly ones work fine

**Comment by hamstu** [comment]
@anafilipadealmeida Curious! I pulled down the branch and it all seemed to be fine, but then that's probably because I have the same timezone that has been hardcoded since the beginning 😅 

Could you share the query `variables` that your browser is sending? Example: 
image

**Comment by anafilipadealmeida** [comment]
> @anafilipadealmeida Curious! I pulled down the branch and it all seemed to be fine, but then that's probably because I have the same timezone that has been hardcoded since the beginning 😅
> 
> Could you share the query `variables` that your browser is sending? Example:
> image

Yes @hamstu , it's "Europe/Lisbon"!

**Comment by hamstu** [comment]
@anafilipadealmeida Can you share all the `variables`? Will help to debug it on my side. (I.e., to see what dates your browser is sending.)

**Comment by anafilipadealmeida** [comment]
Screenshot 2021-07-21 at 16 43 31
Sorry, here it is @hamstu !!

**Comment by anafilipadealmeida** [comment]
Screenshot 2021-07-21 at 16 45 22
Also took one just now on the month query, which is working ok!

**Comment by hamstu** [comment]
Thanks @anafilipadealmeida - [tracking here](https://buffer.atlassian.net/browse/PUB-3727).

**Comment by MayaUribe** [comment]
Hey @anafilipadealmeida 👋 I just merged some changes in the API Gateway mocks that should fix the  issue you are seeing 👀

_Coming from Jira where I left a similar comment 😆_

**Pull request merged**
