### PR TITLE
Remove missing access page

### PR DESCRIPTION
**Pull request by albennett**
## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by karelm** [comment]
Hey @albennett , I can see that removing the component fixes the issue... But should the component be there? Are we fixing the symptom, or the cause. I'm okay fixing the symptom to get us closer to a solution, but we should also fix the cause of the issue if possible too since I would imagine we would like that page there in some scenarios. But I might be wrong. 👍

**Comment by karelm** [comment]
Is the fundamental issue that this user doesn't have a default current organisation and therefore this code didn't work as expected here? If so, perhaps we should do what we did with the old org switcher and select the default org if one doesn't exist, this would then address the fundamental issue we are seeing 🤔

**Comment by albennett** [comment]
Hey @karelm , you're right. We do need to fix the underlying issue. We do get the user data at this point from the app-shell but it looks like currentOrganization from the appShell isn't set, so setting the first one ourselves could fix it for these cases.  We still have the unauthorized redirect logic in place, so it should be ok to leave this logic as-is while I work on the solution.

**Comment by albennett** [comment]
@karelm And thank you for your help on this! I'll take some time going over the currentOrganization logic and how it works and will make sure this problem isn't causing issues with how we're storing the selected org in our redux store.

**Pull request merged**
