### PR TITLE
Upgrade chart version and migrate to multi yaml format

### PR DESCRIPTION
**Pull request by kiriappeee**
### Purpose

To bring the buffer-publish repo into the new form of deployments where developers can manage their own resources.

#### Staging Deployment

_This repo is CI/CD enabled and staging deployment should be available at:
https://<branch_name>.publish.buffer.com :smile:_

### CODE REVIEW

**Comment by kiriappeee** [comment]
image

Confirming that it's working as expected.

**Comment by hamstu** [comment]
@kiriappeee Does this still need to be merged in?

**Comment by kiriappeee** [comment]
@hamstu it does. But it needs some coordination with the team before doing so. It will require some work with Cloudflare, webhooks, and will require everyone to rebase/merge the master branch changes on to their own branches

**Comment by hamstu** [comment]
Ok! Happy to help coordinate this with the team @kiriappeee. Let me know how I can help 😄

**Comment by kiriappeee** [comment]
Thanks @hamstu. Let's work on this in January. Would love to work through the whole process with you so you can see how it works too :)

**Pull request closed without merging**
