### PR TITLE
Scraper: Handle 4xx and 5xx responses as failures

### PR DESCRIPTION
**Pull request by djfarrelly**
## Description
To support the changes with blocking Instagram and Facebook URLs from being fetched via the scraper.

This changes the scrape event to handle 4xx and 5xx responses as errors which prevents the Redux event from being triggered with an empty object. The empty object previously forced the composer to render an empty link attachment.

## Context & Notes
- This is related to the change as described in this thread: [Facebook Data Policy Changes](https://threads.com/34392385234)

## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by hamstu** [comment]
@djfarrelly Do we not need this anymore?

**Comment by djfarrelly** [comment]
Hey @hamstu, this code didn't work as I intended it to - the link attachment still shows and it complains about the error still being uncaught. I didn't have the bandwidth to dig in and I think Di said she'd work on getting this task into Publish's work. If this helps as a starter I can restore the branch. Let me know!

**Comment by hamstu** [comment]
Ah gotcha. Yeah, come to think of it I believe Dianne mentioned this in our grooming chat today. I think I'll probably be working on this after I finish some RevenueCat stuff. 

And no worries re: the branch, I can refer to the diff here so you can leave the branch as is. 👍🏻

**Comment by djfarrelly** [comment]
Sounds good @hamstu!!

**Pull request closed without merging**
