### PR TITLE
[PUB-2004] Tag Awesome users who visit Plans page 

### PR DESCRIPTION
**Pull request by chayjay**
## Description
As above. The user should be untagged after the Appcues tour.

## Context & Notes
[https://buffer.atlassian.net/browse/PUB-2159](https://buffer.atlassian.net/browse/PUB-2159)

## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by hamstu** [comment]
Hey @chayjay – do you still need a review on this? :)

**Comment by chayjay** [comment]
> Hey @chayjay – do you still need a review on this? :)

Hey @hamstu, I _might_. I think this could potentially be useful for triggering the Appcues tour for folx who Awesome users who choose to upgrade.

**Comment by hamstu** [comment]
Let's close this for now @chayjay! We can always come back to it if need be. :)

**Comment by chayjay** [comment]
> Nice @chayjay! The only thing that concerns me are these `package.json` changes 🤔 Did they slip in from a merge or was this intentional?

I think they're from a merge I did for a bug that I ran into a while ago. I'll try removing and seeing if everything works without those changes.

**Comment by hamstu** [comment]
@chayjay Yeah, I'd be wary of keeping those in. I would try to get what's on master for those files and try that. :)

**Pull request merged**
