### PR TITLE
[WIP] Optimize webpack

### PR DESCRIPTION
**Pull request by msanroman**
### Purpose

To reach lightspeed thanks to optimized bundles through webpack 🚀 

### Notes

Hey @hharnisc! Just creating this PR as a possible way to sync our efforts on this sweet hack week project 😄 

### Changelog

- [x] Update to Webpack 4
- [x] Use UglifyJS on production builds - `bundle.js` size is now 4.8M vs 11M (56% decrease in file size).

### Possible improvements?
- [x] Split bundle in two, vendor (for `node_modules` dependencies) and lib (for our own code)?
- [x] Tree shaking
- [ ] Lazy loading by route

### CODE REVIEW

**Comment by hharnisc** [comment]
Hey Mike, leaving this message for you. I've hooked up a side project I'm working on called Payload which I think will be helpful here -- it runs a build and tracks file sizes over time :smile:  -- I'll disconnect it when we finish the hack week. 

I'll leave a longer term note on this PR too that this is just temporary and that we need to have a plan for when people have useful sideprojects. 

(I can see already I need to beef up the machine the worker is deployed on)

**Comment by msanroman** [comment]
Whoa Payload is amazing @hharnisc! So handy for the task at hand 😄

**Comment by hamstu** [comment]
This is so awesome @hharnisc and @msanroman! Can't wait to see this one merged in.

**Comment by msanroman** [comment]
Haha, thanks @hamstu!

@hharnisc - should we give this a go? 😄

**Comment by KatieLo** [comment]
Hey @hharnisc and @msanroman! I've asked some questions on this paper around what it'll take to get this into production, given that it uses a sideproject that's on the earlier side too - https://paper.dropbox.com/doc/Publish-Webpack-Optimization--AJIoJKyP2VtZaDG7Bg26L4mAAg-EeGwFic3YFNMzR38McIYE#:uid=597843950554917708652248&h2=Katie---Thoughts-on-merging-th 
We'll need to figure out these questions (and probably some others I haven't thought of) before it feels good to deploy this to Publish users as-is. 

If we disconnect Payload then I don't see any concerns with merging :)

**Comment by KatieLo** [comment]
@hharnisc following on from the paper - 👍 to merge it if PayLoad is disconnected. 

We'll continue the side project convo with Joel's input!

**Comment by hharnisc** [comment]
@KatieLo @msanroman all payload related changes are gone and payload has been disconnected for a while now :smile: 

I've rebased and tested the changes from master. Going to merge this one now :green_apple:

**Pull request merged**
