### PR TITLE
Copy adjustments on empty state, tooltip, using lowercase "campaigns" when talking about user's content

### PR DESCRIPTION
**Pull request by letsbleachthis**
## Description

Updating View Campaign empty state banner copy, the tooltip copy  in the composer, and following a new rule: 

- Use uppercase 'C' in Campaign when referencing the feature
- Use lowercase 'c' in campaign when referencing a user's content

## Context & Notes

Jira card: https://buffer.atlassian.net/browse/PUB-2662

## Screenshots (if appropriate)
Image 2020-04-10 at 10 34 41 AM

## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by hamstu** [comment]
Love seeing you drop edits like this @letsbleachthis! 🚀 🏆

**Comment by letsbleachthis** [comment]
Hey @hamstu! I'm not sure why the Travis CI build keeps failing 🤔 I've run `yarn run test-update`, and `yarn run test`, and it looks like everything is passing. Is there something else I should be checking for?

**Comment by anafilipadealmeida** [comment]
> Hey @hamstu! I'm not sure why the Travis CI build keeps failing 🤔 I've run `yarn run test-update`, and `yarn run test`, and it looks like everything is passing. Is there something else I should be checking for?

Hey @letsbleachthis, it seems there are snapshots still failing. Let me try updating them and push to your branch 🙂

**Comment by letsbleachthis** [comment]
> > Hey @hamstu! I'm not sure why the Travis CI build keeps failing 🤔 I've run `yarn run test-update`, and `yarn run test`, and it looks like everything is passing. Is there something else I should be checking for?
> 
> Hey @letsbleachthis, it seems there are snapshots still failing. Let me try updating them and push to your branch 🙂

Dangit, I thought I was in the clear! @anafilipadealmeida If I see this in my terminal (https://share.buffer.com/WnuGeE15), should I ignore the message that says how many tests pass, and look at anything above it in red to assume there's an issue?

**Comment by anafilipadealmeida** [comment]
> https://share.buffer.com/WnuGeE15

I believe you @letsbleachthis 😂 Here in travis and when I pulled the branch there were 13 failing, but they seemed related to a change that is already deployed. I pushed them to your branch so it should be fine! I'd say in the future we should confirm if you are in the latest yarn version, run yarn after pulling master just to be safe, and in case it feels like something weird with snapshots is happening (like failed snapshots that seem to be related to other PRs recently deployed), just pull the latest master into your branch (git pull origin master), run yarn and then yarn run test to see if something changed

**Comment by letsbleachthis** [comment]
> > https://share.buffer.com/WnuGeE15
> 
> I believe you @letsbleachthis 😂 Here in travis and when I pulled the branch there were 13 failing, but they seemed related to a change that is already deployed. I pushed them to your branch so it should be fine! I'd say in the future we should confirm if you are in the latest yarn version, run yarn after pulling master just to be safe, and in case it feels like something weird with snapshots is happening (like failed snapshots that seem to be related to other PRs recently deployed), just pull the latest master into your branch (git pull origin master), run yarn and then yarn run test to see if something changed

Ahhh, my yarn version _was_ out of date. Thank you!

**Pull request merged**
