### PR TITLE
Task/remove perf tracking

### PR DESCRIPTION
**Pull request by federicoweber**
Remove performance tracking middleware and rpc endpoint

## Context & Notes
This is needed because performance tracking is using DD custom metrics, and we want to reduce those. Read https://threads.com/34367286276 for more context

## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by federicoweber** [comment]
That's interesting tests are complaining about missing `@bufferapp\performance-tracking` but that is not required by the updated version of `@bufferapp\analyze-profile-selector`, it seems like it's not pulling the new package. Will look into it tomorrow.

**Comment by albennett** [comment]
Ah, yes that's strange. It looks like both versions are appearing in the `yarn.lock` file. 🤔 I can help look into this later too @federicoweber

**Comment by albennett** [comment]
Hey @federicoweber I went ahead and updated all the analyze package versions. I think some of the other packages were referencing the `0.87.2 analyze-profile-selector` package, which still referenced the `performance-tracking` package. Everything should be good now! 😄

**Comment by federicoweber** [comment]
Great catch @albennett you are awesome, thank you 🙌.

**Pull request merged**
