### PR TITLE
[PUB-2999] Delete references to feature flips 100% rolled out or not used

### PR DESCRIPTION
**Pull request by anafilipadealmeida**
## Description
Delete references to feature flips 100% rolled out or not used:
 - hasIGLocationTaggingFeature: 100% rolled out
- hasIGDirectVideoFlip: 100% rolled out
- has_simplified_free_plan_ux: nobody has it

## Context & Notes
https://buffer.atlassian.net/browse/PUB-2999

## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by anafilipadealmeida** [comment]
This is a great comment @hamstu ! There are some things I found out with this PR:
1) I don't think any free users will get the share next button 😂 I've made some tests with my account after making the changes and the behavior was still the same, so I went to the code and realized that this is where the share next is being handled: https://github.com/bufferapp/buffer-publish/blob/master/packages/composer/interfaces/buffer-publish.jsx#L50-L51. With that in mind, I made the decision to not spend more time trying figure out why that code in the composer utils exists, as it's a different matter.
2) I'm not sure free users who are not team members have it. I've impersonated some and none has it. Last month I've changed `has_simplified_free_plan_ux: userData.features.includes('has_simplified_free_plan_ux' )` to `has_simplified_free_plan_ux: false` but if it existed it would still come in the features array. I've also ran the query https://app.redash.io/buffer/queries/431672/source for it and nothing showed. I do agree it would be less confusing to address it not as a feature flip, but it was supposed to be received in the features array and nobody seems to have it 🤷‍♀️

One thing I can do is to keep track of these things (since they are out of the scope for the org switcher/user parser clean up) and by the end of the cleanup story bring them to the team so we can decide which ones should be converted to jira tickets. How do you feel about it? Anything I might be missing? 😅

**Comment by hamstu** [comment]
Thanks for the great response @anafilipadealmeida!

> so I went to the code and realized that this is where the share next is being handled [...]

Haha, I should have known with the composer. It's like Inception, too many layers deep. 😂  Good find!

> but if it existed it would still come in the features array

As far as I can tell there's never been a feature `has_simplified_free_plan_ux`, do you have a referenc to somewhere in the code where we search for a feature with that name? 

> One thing I can do is to keep track of these things (since they are out of the scope for the org switcher/user parser clean up) and by the end of the cleanup story bring them to the team so we can decide which ones should be converted to jira tickets. How do you feel about it? Anything I might be missing? 😅

Agreed! I don't want to bikeshed on this little thing too much. Let's table it for now and we can revisit in future clean ups. 😄

**Comment by anafilipadealmeida** [comment]
@hamstu I went back some months in github to make sure it wasn't something I had changed by mistake: https://github.com/bufferapp/buffer-publish/blob/b0f2e1dd18430306d6403bac4a7d07b9f2b878a9/packages/server/parsers/src/userParser.js#L52-L54
Maybe it never worked? 😅

**Comment by hamstu** [comment]
Ooh, good find! 😲 

> Maybe it never worked? 😅

Yeah! I can't see any evidence that it would have worked. Well all the more reason to remove it now!

**Pull request merged**
