### PR TITLE
[PUB-3191] Change preserve composer state to true on initialize

### PR DESCRIPTION
**Pull request by albennett**
## Description
Preserve the state when clicking outside of the composer editor. 

We were previously only preserving the text the second time the composer is closed.
https://buffer.atlassian.net/browse/PUB-3191

## Context & Notes

With the org switcher, we need to check whether the org has switched and reset the data in the composer if true. The best solution I could find was sending an additional value to the composer and adding it to the reset data conditions.
## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Review by hamstu — APPROVED** [review]
Good fix! Thanks for taking care of this @albennett. 🚀  LGTM.

**Comment by albennett** [comment]
Hey @hamstu I was testing this a bit more in staging and it looks like there's still an issue with preserving state once we've switched orgs. I'm going to take another look at this tomorrow.

**Comment by albennett** [comment]
Hey @hamstu I worked on this again over the weekend and will re-request another review. This composer bug was tricky 😅 With the org switcher, we need to check whether the org has switched and reset the data in the composer if it has. The best solution I could find was sending an additional value to the composer and adding it to the reset data conditions.

**Review by hamstu — APPROVED** [review]
This looks great @albennett. I really appreciate the naming here too, I feel like it's much more clear what's happening.

✅ LGTM!

**Comment by EricBorelandMC** [comment]
hi

**Pull request merged**
