### PR TITLE
[PUB-3581] Replace hyphen in date range with en-dash

### PR DESCRIPTION
**Pull request by guldenmw**
### Description

Replace hyphen in Calendar date range with en-dash

### Context & Notes

It's recommended to use en-dash to show ranges in numbers and dates
https://buffer.atlassian.net/browse/PUB-3581

### Screenshots (if appropriate)
image

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
image

### CODE REVIEW

**Review by anafilipadealmeida — COMMENTED** [review]
This change impacts one test we have, you'll need to update it 🙂

**Comment by guldenmw** [comment]
Tisk tisk tisk Mw. Didn't even check for or run tests. 50 points from Gryffindor.

**Comment by anafilipadealmeida** [comment]
> Tisk tisk tisk Mw. Didn't even check for or run tests. 50 points from Gryffindor.

That's why we have a pre-deploy checklist and the tests running in here as well 😂 To make sure we don't forget them!

**Review by anafilipadealmeida — APPROVED** [review]
Looking great @guldenmw!!

**Pull request merged**
