### PR TITLE
[PUB-3513] Add Week and Month toggle to calendar page

### PR DESCRIPTION
**Pull request by guldenmw**
### Description

Add toggle to calendar page using Segmented Control component that switches between the Week and Month calendar view

### Screenshots (if appropriate)
image

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [x] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [x] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [x] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [x] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
image

### CODE REVIEW

**Review by anafilipadealmeida — COMMENTED** [review]
Hey @guldenmw, I have one question only: shouldn't the segmented control have a height of 40px, like the selects, instead of 44px? 
Screenshot 2021-07-19 at 11 38 48

**Comment by guldenmw** [comment]
@anafilipadealmeida You're right, it should be! Let me investigate.

**Comment by guldenmw** [comment]
@anafilipadealmeida It seems it was a misstep on my part on the actual Segmented Control component. The designs are using an inner border instead of adding a px to the outside, which accounts for 2px (1px top border 1px bottom border). We also have a focus state, which adds a border around the option component which is set to transparent when not focused. That's the other 2px for top and bottom. I need to reduce the parent component and option component padding.

**Review by anafilipadealmeida — APPROVED** [review]
Let's do this! 🚀

**Pull request merged**
