### PR TITLE
[PUB-2176] Disable Payday page experiment

### PR DESCRIPTION
**Pull request by chayjay**
## Description

Disabling the control version of the Payday page experiments in favor of showing every Pro user the enabled version of the experiment.

## Context & Notes
[https://buffer.atlassian.net/browse/PUB-2176?atlOrigin=eyJpIjoiMTg5YTM2MDljMjc3NDRjMmE5NDkyODEzN2E0MjEzZmEiLCJwIjoiaiJ9](https://buffer.atlassian.net/browse/PUB-2176?atlOrigin=eyJpIjoiMTg5YTM2MDljMjc3NDRjMmE5NDkyODEzN2E0MjEzZmEiLCJwIjoiaiJ9)

## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by anafilipadealmeida** [comment]
Hey @chayjay, just out of curiosity: we are deleting the PlanColumnExperimentControl for good? Is the PlanColumnExperimentControl still being used as experimental, or is it supposed to be definitive? 🙂

**Comment by chayjay** [comment]
> Hey @chayjay, just out of curiosity: we are deleting the PlanColumnExperimentControl for good? Is the PlanColumnExperimentControl still being used as experimental, or is it supposed to be definitive? 🙂

Hey @anafilipadealmeida, great question! I believe this to be definitive as the experiment has proven that the enabled version of the experiment has produced more MRR overall ☺

**Comment by anafilipadealmeida** [comment]
> > Hey @chayjay, just out of curiosity: we are deleting the PlanColumnExperimentControl for good? Is the PlanColumnExperimentControl still being used as experimental, or is it supposed to be definitive? 🙂
> 
> Hey @anafilipadealmeida, great question! I believe this to be definitive as the experiment has proven that the enabled version of the page has produced more MRR overall ☺

Gotcha! 😄 In that case I'd suggest you to replace the name of `PlanColumnExperimentEnabled` component by something more definitive, to avoid confusion with future experiments 🙂

**Comment by chayjay** [comment]
> > > Hey @chayjay, just out of curiosity: we are deleting the PlanColumnExperimentControl for good? Is the PlanColumnExperimentControl still being used as experimental, or is it supposed to be definitive? 🙂
> > 
> > 
> > Hey @anafilipadealmeida, great question! I believe this to be definitive as the experiment has proven that the enabled version of the page has produced more MRR overall ☺
> 
> Gotcha! 😄 In that case I'd suggest you to replace the name of `PlanColumnExperimentEnabled` component by something more definitive, to avoid confusion with future experiments 🙂

Ah, yes! I was thinking it would be a good idea to rename but I didn't have any idea what it might be renamed to. If my renaming is confusing please let me know and I can continue thinking of better options 🙌🏾

**Comment by anafilipadealmeida** [comment]
> Ah, yes! I was thinking it would be a good idea to rename but I didn't have any idea what it might be renamed to. If my renaming is confusing please let me know and I can continue thinking of better options 🙌🏾

The name you chose seems pretty clear to me! 😄 You'll probably just need to update the snapshots, but otherwise all good!

**Pull request merged**
