### PR TITLE
[PUB-1879] Add Reply cross-upgrade path in Sent Posts

### PR DESCRIPTION
**Pull request by albennett**
## Description
Add Reply cross-upgrade path in Sent Posts

- Customers in Publish who have the Sent Posts stats bar (currently Pro and up customers) and have a post in Instagram Business or Facebook Page that has more than 0 comments should see a "Engage" button show that takes them to reply. Reply is handling the logic for what view the user will see depending on if they're a Reply customer. 

https://buffer.atlassian.net/browse/PUB-1879

## Context & Notes
Hey @karelm This change was a reminder of how redundant it is to pass a new value into all of the different Post types. 😅I'm going to think more on some possible refactors for the future. 

Also @karelm & @CoxyBoris, I'm going to be out next week 🏝 I know the Reply changes may wait until next week. @CoxyBoris Would you be up for reaching out to @karelm when this PR is ready to be deployed?

## Screenshots (if appropriate)
https://hi.buffer.com/cc9f5ee6c9f8
## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [x] I have commented my code, particularly in hard-to-understand areas.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by karelm** [comment]
> Hey @karelm This change was a reminder of how redundant it is to pass a new value into all of the different Post types. 😅I'm going to think more on some possible refactors for the future.

Hey @albennett, with regard to your comment quoted. I took a look at your work and it doesn't seem that bad around prop spreading, at least its clear where the props are being used, and where they come from, I think the larger problem is that we aren't composing our components at the right level, but just nesting and nesting.

If instead of writing our components with their dependencies inside, we should instead create them like isolated containers.

```
// filea.js
const SomeComponent = ({classname, height, children}) => {
    return (
        <div className={classname} style={someStyleHelper(height)> 
            {children}
        </div>
    );
};
// fileb.js
const OtherComponent = ({label, children}) => {
    return (
        <React.Fragment>
            <label>{label}</label>
            {children}
        </React.Fragment>
    );
}
```

This would then allow us to create shallow nested components, and use them however we wanted.

```
import OtherComponent from 'fileb';
import SomeComponent from 'filea';

({classname, height, label}) => {
    if(height > 1) {
        return (
            <SomeComponent classname={classname} height={height}>
                <OtherComponent label={label}>
                    <input type="text" />
                </OtherComponent>
            </SomeComponent>
        );
    } else {
        return (
            <OtherComponent label={label}>
                <SomeComponent classname={classname} height={height}>
                    <input type="text" />
                </SomeComponent>
            </OtherComponent>
        );
    }
}
``` 
these components then have the ability to be structured in a lot flatter of a heirarchy, and you can isolate the scope of the component more appropriately.

I'm not sure this is 100% clear, but hopefully it will give you something to consider. I'm happy to chat more on this later with you if its not clear 😄

**Comment by albennett** [comment]
Hey @karelm thanks for such a well thought out response! Agreed, my pain point was more around how nested all of the components are, which results in us having to pass a prop in several places. I like your suggestion. I'm going to try refactoring it in a different PR, so it's not a blocker in case I don't finish it by tmr (leaving a bit early to catch a ✈️ )

**Comment by karelm** [comment]
Yes, thats totally fine @CoxyBoris, let me know when you are happy for it to go live and we can take care of that, no rush on my part 👍

**Comment by albennett** [comment]
Hey @CoxyBoris @karelm just wanted to reach out about the status of this PR. Are we waiting on Reply changes?

**Comment by CoxyBoris** [comment]
Heya @albennett ! So sorry sorry the delay with this PR, we should complete the work this week. However with the codefreeze next week I'm not 100% sure we'll deploy it on our side but we'll do our best! Is that an issue for you to leave that PR open for now?

**Comment by albennett** [comment]
Hey @CoxyBoris no worries at all! I was out last week so just wanted to check on the status 😀 No rush from our side! I'm move the jira card to blocked.

**Pull request closed without merging**
