### PR TITLE
[PUB-3709] Update GraphQL queries and data processing to support new format

### PR DESCRIPTION
**Pull request by anafilipadealmeida**
### Description
- Remove type
- Change name
- Bonus: add campaigns to queries

### Context & Notes
https://buffer.atlassian.net/browse/PUB-3709

### Best Practices Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
image

### CODE REVIEW

**Comment by anafilipadealmeida** [comment]
@hamstu, I used the https://pub-3706-mock-graph.dev.buffer.com/ locally as `GRAPHQL_MOCK_API` in our webpack files, just to test, but it was returning the error: `Field CalendarInput.type of required type CalendarResponseType! was not provided.`

**Comment by hamstu** [comment]
@anafilipadealmeida I don't see the new URL in this PR. Or did you not commit that? That error sounds like it's still using the old endpoint.

**Comment by anafilipadealmeida** [comment]
I didn't commit, was I supposed to do so?

**Comment by hamstu** [comment]
@anafilipadealmeida Oh no, as in you don't need to merge that URL into `main`, but I was just asking in case the file wasn't changed somehow! Anyway, I think I may not what the issue is – will check and come back here in a sec.

**Comment by hamstu** [comment]
@anafilipadealmeida I ran this locally:

```
export GRAPHQL_MOCK_API="https://pub-3706-mock-graph.dev.buffer.com/" && yarn run watch:mock
```

(This is the same as [changing it directly here](https://github.com/bufferapp/buffer-publish/blob/eb5a131ce90c0a0b4567376ec041a928021df825/webpack.config.dev.js#L60), since the `webpack.EnvironmentPlugin` will look for existing env vars before falling back to what's defined.)

✅  And it worked for me.

**Comment by anafilipadealmeida** [comment]
Great to know @hamstu!

**Review by hamstu — APPROVED** [review]

**Pull request merged**
