### PR TITLE
PUB-2655  | Filtering channels to get the channel per item with all details

### PR DESCRIPTION
**Pull request by MayaUribe**
## Description

Filtering channels to get the channel per item with all details.

## Context & Notes

JIRA card: PUB-2655

## Screenshots
Image 2020-04-14 at 4 16 28 PM

## Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

### CODE REVIEW

**Comment by MayaUribe** [comment]
@anafilipadealmeida I tried not to make too much changes here considering you are working in that same file 🙂

**Comment by anafilipadealmeida** [comment]
Hey @MayaUribe, would you mind taking a look at this PR? https://github.com/bufferapp/buffer-publish/pull/1323. I might have fixed it there 😅 I moved all the profile props we use to the index.js campaign file, instead of having some in the campaigns parser with channels

**Comment by MayaUribe** [comment]
> Hey @MayaUribe, would you mind taking a look at this PR? #1323. I might have fixed it there 😅 I moved all the profile props we use to the index.js campaign file, instead of having some in the campaigns parser with channels

That sounds great @anafilipadealmeida I'll take a look :)

**Comment by MayaUribe** [comment]
Closing this branch since its fixed with the changes in this PR https://github.com/bufferapp/buffer-publish/pull/1323

**Pull request closed without merging**
