### PR TITLE
Bump @bufferapp/components to 3.1.0

### PR DESCRIPTION
**Pull request by twanlass**
### Purpose
Use the latest `@bufferapp/components` package which includes a fix for the `fontSizeMini` constant. `fontSizeMini` will now compute to `14px` (previously computed to a float value). 

#### Staging Deployment

_This repo is CI/CD enabled and staging deployment should be available at:
https://<branch_name>.publish.buffer.com :smile:_

### CODE REVIEW

**Comment by hamstu** [comment]
@twanlass Are you interested in setting up your local dev to prep this one? If not let me know and I'll carve out some time to do it 😄

**Comment by twanlass** [comment]
Heya @hamstu!

Setting up a local dev is on my list this week (so I can contribute some style polish). Happy to give it a go then 😄. 

Up for sharing any steps I'll need to follow to get this changed rolled out? 🙏

**Comment by hamstu** [comment]
Sounds good @twanlass! Once you've got your local environment running you'll want to run:

```bash
# install deps
$ yarn

# build the local bundle
$ yarn run watch

# now open https://publish.local.buffer.com locally, to confirm all looks good

# stop, the watch command
# update the test snapshots
$ yarn run test-update

# commit and push any changed files.
```

If that all goes well you can push to this branch and confirm again on the dev branch that it's al ok.

**Comment by hamstu** [comment]
Let me know when I can help you out with this @twanlass! (No rush, I know we're in a bit of a dash to the finish line right now! Let's catch up next month if you need any help here.)

**Comment by twanlass** [comment]
Heya @hamstu – all looks good on my end. Up for sharing the merge + deploy process?

**Pull request merged**
